USE [master]
GO
/****** Object:  Database [ServiceOrders]    Script Date: 2/9/2023 2:28:42 PM ******/
CREATE DATABASE [ServiceOrders]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ServiceOrders', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ServiceOrders.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ServiceOrders_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ServiceOrders_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ServiceOrders] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ServiceOrders].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ServiceOrders] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ServiceOrders] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ServiceOrders] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ServiceOrders] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ServiceOrders] SET ARITHABORT OFF 
GO
ALTER DATABASE [ServiceOrders] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ServiceOrders] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ServiceOrders] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ServiceOrders] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ServiceOrders] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ServiceOrders] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ServiceOrders] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ServiceOrders] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ServiceOrders] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ServiceOrders] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ServiceOrders] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ServiceOrders] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ServiceOrders] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ServiceOrders] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ServiceOrders] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ServiceOrders] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ServiceOrders] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ServiceOrders] SET RECOVERY FULL 
GO
ALTER DATABASE [ServiceOrders] SET  MULTI_USER 
GO
ALTER DATABASE [ServiceOrders] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ServiceOrders] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ServiceOrders] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ServiceOrders] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ServiceOrders] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ServiceOrders] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ServiceOrders', N'ON'
GO
ALTER DATABASE [ServiceOrders] SET QUERY_STORE = OFF
GO
USE [ServiceOrders]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 2/9/2023 2:28:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[CustomerName] [nvarchar](50) NOT NULL,
	[Description] [text] NOT NULL,
	[CreatedAt] [datetime] NOT NULL,
	[Status] [tinyint] NOT NULL,
 CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Orders] ADD  CONSTRAINT [DF_Orders_CreatedtAt]  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Orders] ADD  CONSTRAINT [DF_Orders_Status]  DEFAULT ((0)) FOR [Status]
GO
USE [master]
GO
ALTER DATABASE [ServiceOrders] SET  READ_WRITE 
GO
